apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cert-manager-app
  name: cert-manager-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cert-manager-app
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cert-manager-app
  name: cert-manager-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cert-manager-app
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: certmanagerapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - www.bettercallpavan.com
    secretName: bettercallpavan-com-tls
  rules:
  - host: www.bettercallpavan.com
    http:
      paths:
      - path: /app
        backend:
          serviceName: cert-manager-app
          servicePort: 80
