apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-monkey-experiment
    kube-monkey/enabled: enabled
    kube-monkey/mtbf: '1'
    kube-monkey/identifier: 'kube-monkey-experiment'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: '1'
  name: kube-monkey-experiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-monkey-experiment
  template:
    metadata:
      labels:
        app: kube-monkey-experiment
        kube-monkey/enabled: enabled
        kube-monkey/mtbf: '1'
        kube-monkey/identifier: 'kube-monkey-experiment'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: '1'
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
