---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api-prod
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm-charts/web-app
      sourceRef:
        kind: GitRepository
        name: flux-system
  install: {}
  interval: 1m0s
  values:
    replicaCount: 2
    nameOverride: "api"
  valuesFiles:
    - ./prod/environments/image.yaml
