---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-prod
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm-charts/web-app
      sourceRef:
        kind: GitRepository
        name: flux-system
  install: {}
  interval: 10m0s

