---
apiVersion: v1
data:
  locustfile.py: "from locust import HttpUser, task, between\n\nclass HelloWorldUser(HttpUser):\n
    \   wait_time = between(0.5, 2.5)\n\n    @task(3)\n    def health(self):\n        response
    = self.client.get('/api/health')\n        if (response.status_code == 200):\n
    \           print(\"Health request Success\")\n    \n    @task(6)\n    def login(self):\n
    \       response = self.client.post(\"/login\", data = {\"username\":\"admin\",
    \"password\":\"prom-operator\"})\n        if (response.status_code == 200):\n
    \           print(\"Login Success\")\n"
kind: ConfigMap
metadata:
  name: my-loadtest-locustfile
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: locust-isolated
  labels:
    app.kubernetes.io/name: locust
    app.kubernetes.io/instance: locust
    load_test: my-loadtest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-config
  labels:
    app.kubernetes.io/name: locust
    app.kubernetes.io/instance: locust
    load_test: my-loadtest
data:
  docker-entrypoint.sh: |
    #!/bin/sh

    set -eu

    exec /usr/local/bin/locust $@
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-lib
  labels:
    app.kubernetes.io/name: locust
    app.kubernetes.io/instance: locust
    load_test: my-loadtest
data:
  {}
---
apiVersion: v1
kind: Service
metadata:
  name: locust
  labels:
    app.kubernetes.io/name: locust
    app.kubernetes.io/instance: locust
    load_test: my-loadtest
    component: "locust-isolated"
spec:
  type: ClusterIP
  ports:
  - name: master-p1
    port: 5557
    protocol: TCP
    targetPort: 5557
  - name: master-p2
    port: 5558
    protocol: TCP
    targetPort: 5558
  - name: master-p3
    port: 8089
    protocol: TCP
    targetPort: 8089
  - name: metrics
    port: 9646
    protocol: TCP
    targetPort: 9646
  selector:
    component: locust-isolated
    load_test: my-loadtest
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: locust-metrics-servicemonitor
  labels:
    type: locust-master
spec:
  selector:
    matchLabels:
      load_test: my-loadtest
  endpoints:
  - port: metrics
    interval: 5s
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: locust-load-test
spec:
  jobTemplate:
    metadata:
      labels:
         component: locust-isolated
         load_test: my-loadtest
      name: locust-load-test
    spec:
      template:
        metadata:
          labels:
            component: locust-isolated
            load_test: my-loadtest
        spec:
          serviceAccountName: locust-isolated
          containers:
          - name: locust-exporter 
            image: "containersol/locust_exporter"
            ports:
              - containerPort: 9646
                name: locustm-met
          - name: locust
            securityContext:
                {}
            image: "locustio/locust:latest"
            command:
            - sh
            - /config/docker-entrypoint.sh
            args:
            - --autostart --users 100 --spawn-rate 100 -t 240s --host http://192.168.29.168/ --print-stats --autoquit 10
            imagePullPolicy: IfNotPresent
            resources:
              {}
            volumeMounts:
              - name: locustfile
                mountPath: /mnt/locust
              - name: lib
                mountPath: /mnt/locust/lib
              - name: config
                mountPath: /config
            env:
              - name: LOCUST_HOST
                value: "http://192.168.29.168/"
              - name: LOCUST_LOGLEVEL
                value: "INFO"
              - name: LOCUST_LOCUSTFILE
                value: "/mnt/locust/locustfile.py"
            ports:
              - containerPort: 8089
                name: loc-master-web
                protocol: TCP
              - containerPort: 5557
                name: loc-master-p1
                protocol: TCP
              - containerPort: 5558
                name: loc-master-p2
                protocol: TCP
          restartPolicy: OnFailure
          volumes:
            - name: lib
              configMap:
                name: locust-lib
            - name: locustfile
              configMap:
                name: my-loadtest-locustfile
            - name: config
              configMap:
                name: locust-config
  schedule: '*/5 * * * *'
  concurrencyPolicy: Replace
